### ISSUE TITLE
BB8 APIS

### ISSUE THREAD

**Issue by mvaloriani** [orbotix/Sphero-Win-SDK#11]
Hi,

I'm trying to use Sphero BB8 with the APIs, but RobotProvider doesn't find it.

**Comment by Jamaslab** [comment]
Hello,
Are there any news about the support for the Sphero BB8?

**Comment by scheckley** [comment]
+1

**Comment by iamcgn** [comment]
Thanks for reaching out about our SDK. Unfortunately we are not able to open up our Windows SDK to connect to BB-8. We want to ensure the authenticity of BB-8 the character that you see on screen.

**Comment by ridecar2** [comment]
Now that the [javascript SDK](https://github.com/orbotix/sphero.js) supports the BB-8 robot will you be reconsidering and allowing the Windows SDK to connect to it?
