### ISSUE TITLE
LocationUpdatedEvent never fires

### ISSUE THREAD

**Issue by benheymink** [orbotix/Sphero-Win-SDK#2]
I've written a sample which can successfully get gyro and accelerometer data back from the Sphero, much like the included sample. However, upon adding the following line:

m_robot.SensorControl.LocationUpdatedEvent += LocationUpdatedEvent; 

Seems to:
A) Never actually fire for location events, and
B) stop gyro and accelerometer events from firing.

Any ideas? I realise this is probably more of a misunderstanding of the SDK than a code issue, so feel free to point me somewhere else!
Win8.1 Build 9431

**Comment by MinitechnicusM** [comment]
Have same problem.
Please, could we have a function that sends the commands like Macros? That would be easier for the library developer as well fro SDK users.

**Comment by iamcgn** [comment]
Thank you for your interest in our SDK. We are working on an updated Windows 10 UWP SDK that will address many of the issues with the current SDK and add support for Bluetooth Low Energy. We don't have an estimated release date at this time but we are actively working to revive this project.

**Comment by benheymink** [comment]
Hell, I've waited three years for a response, whats 3 years more?
