### ISSUE TITLE
Low-Level control

### ISSUE THREAD

**Issue by PaulFreund** [orbotix/Sphero-Win-SDK#4]
Hi, I started to write a Windows 8.1 app which can control the Sphero 2.0 - [SpheroControl](https://github.com/PaulFreund/SpheroControl) (Xbox360 gamepad input only at the moment)

At the moment it works but it does not feel very good and without calirbration its very hard to use.

I want to controls to feel as "natural" as possible and I think I can't achieve this by just using the Roll and SetHeading functions. In the API docs I read that the basic movement is controlled by two wheels and that it is possible to control the Sphero in a more basic way. I also read about orbBasic which seems to be a very good way to optimize the responses and behaviour.

Is there a way I can control the Sphero in a more detailed way with this SDK or would I have to write my own Bluetooth protocol wrapper?

**Comment by iamcgn** [comment]
Thank you for your interest in our SDK. We are working on an updated Windows 10 UWP SDK that will address many of the issues with the current SDK and add support for Bluetooth Low Energy. We don't have an estimated release date at this time but we are actively working to revive this project.
