### ISSUE TITLE
What's the roadmap for Win-SDK?

### ISSUE THREAD

**Issue by vinjn** [orbotix/Sphero-Win-SDK#8]
I am planning to use Sphero on Windows.

[Android-SDK](https://github.com/orbotix/Sphero-Android-SDK/tree/beta) is regularly updated, however Win-SDK is very outdated.

**Comment by tazdon** [comment]
I would also like to know the progress on the Windows SDK for Ollie

**Comment by iamcgn** [comment]
Thank you for your interest in our SDK. We are working on an updated Windows 10 UWP SDK that will address many of the issues with the current SDK and add support for Bluetooth Low Energy. We don't have an estimated release date at this time but we are actively working to revive this project.

**Comment by tazdon** [comment]
Cool, let me know if you need a beta tester.
