### ISSUE TITLE
Support of Windows Desktop application development

### ISSUE THREAD

**Issue by CKuhnt** [orbotix/Sphero-Win-SDK#9]
As already mentioned in issue #5, I am looking for the support of Windows' .NET Framework, too. All existing SDKs are either supporting only mobile platforms or only suitable to build Apps. Unfortunately there is no SDK which supports Windows on a PC without additional overhead (Unity).

I try to use Sphero 2.0 in a Windows 8.1 Desktop application. However, I cannot add a reference to RobotKit.dll because it is targeting ".NET Framework" instead of ".NET Core", since it is not an Windows App. 
The application is going to handle some computational efforts by reading sensor data from another Bluetooth device, resulting in commands for the Sphero. Moreover it stores some data in a database and, if possible, connects to up to 4 Bluetooth devices and Spheros. That is why I need the power of a PC, hence a real Desktop application.
Additionally, I wont need much graphics, so I don't need Unity and its SDK. 

Being confronted with ".NET Core" the first time, I've been reading about Portable Class Libraries, which would be a more platform-independent and, perhaps, an easy way to accomodate - see [MSDN Blogs: Sharing Code across Platforms](http://blogs.msdn.com/b/dotnet/archive/2014/04/21/sharing-code-across-platforms.aspx).

I am looking forward to hear from you, despite of not seeing any activity for 2 years in this project. I hope you have not lost interest in it. But if, why not publish the source to the community and let them do the work? ;)

**Comment by iamcgn** [comment]
Thank you for your interest in our SDK. We are working on an updated Windows 10 UWP SDK that will address many of the issues with the current SDK and add support for Bluetooth Low Energy. We don't have an estimated release date at this time but we are actively working to revive this project.
